# f_name= input ('Enter your first name: ')
# l_name= input ('Enter your last name')
# print(f_name+ l_name)
# fname= input ("Enter your first name: ")
# lname= input ("Enter your last name: ")
# print(fname + lname)
# fname= input ("Enter your first name: ")
# lname= input ("Enter your last name: ")
# print(fname  +' '+ lname)
age = int(input("what\'s ur age: "))
print(type(age))